name: Sincronizacion Automatica Portatil Chile

on:
  schedule:
    # Se ejecuta automáticamente cada 30 minutos
    - cron: '*/30 * * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente con un clic

jobs:
  ejecutar-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v3

      - name: Configurar entorno Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Google Chrome y librerias
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install selenium pandas

      - name: Ejecutar script de extraccion
        run: python scraper.py

      - name: Guardar cambios en el repositorio
        run: |
          git config --global user.name "Bot Automagico"
          git config --global user.email "bot@github.com"
          git add catalogo_portatil_chile.csv
          git commit -m "Actualización automática de catálogo y precios" || exit 0
          git push
